server:
  port: 8081
spring:
  application:
    name: Popova
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${JDBC_USER}
    password: ${JDBC_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jwt:
    secret: PopovaMariaAleksandrovna1BIB22150
    expiration: 3600000